GET http://172.30.13.177:30013/x-data-resource-service/v1/resources/data-provider/om_region?columns=code%2Cregion_code%2Cregion_name%2Cregion_path&filter=region_name%3D'%E6%97%A0%E9%94%A1%E5%B8%82'
accept: application/json;charset=UTF-8
x-token: eyJ1c2VyIjoiY2NiZmVkYzgwMTYzYzAwN2IxNjkzZjlmYzgxYWU1MjMiLCJ1c2VyTmFtZSI6IueuoeeQhuWRmCIsIm9yZ2FuaXphdGlvbk5hbWUiOiLkupHnspLmmbrmhaciLCJleHBpcmVkX3RpbWUiOiIyMDIwLTEwLTIxIDA1OjMwOjEwIiwic2lnbmF0dXJlIjoiUW1ncWM2Y3FEcVZPRjJZeWZMdTAzMGY5NkFoV2VHNVQycHF5blk1eHNULTlUMUlGOWF2NEZJQUktWjR0RElkcUF3OXpWWERzUVV3bm54MFEwbkJ1WmpTczJMQWNPNHNsYl96ZEl0UWRjVHJJbFJuaHY4LW9QYXZtLTR4cHhyQy03SWV1MXR2MlVTVWhBV3E4dFUzTWRfNGI0VVdDZ00waHlId3dkV3ltMmVJPSJ9


###
post http://localhost:9090/api/middata/invokeOrginList
Content-Type: application/x-www-form-urlencoded

tableName=adm_zhslyzt_lake&whereCond=lk_name like concat('%','湖','%') &queryFields=lk_name,lk_code,lk_loc

### 取水站
get http://localhost:19003/api/station/fetchwater/list?watershed=&regionCode=&keyword=

### 雨量站
get http://localhost:19003/api/station/rainfall/list?watershed=&regionCode=&keyword=

### 雨量站
get http://localhost:19003/api/station/rainfall/list?watershed=&regionCode=&keyword=
